[general]
;IME 修复方案，只有0和1两种，优先尝试方案1（更完美），如果会卡门再尝试方案0
imeType=1
;服务器地址
ServerIP_Address=127.0.0.1
serverIP_Port=8484
;窗口模式（Win10/11 建议开启，全屏易导致 DX8 启动失败 0x80004005）
WindowedMode=true
;跳过开头动画
RemoveLogos=true
;隐藏顶部滚动公告条
HideSlideNotice=true
;Should VirtuProtect be enabled? (true/false, default true) (this is necessary for clients without CRC bypass such as hendi's clients
;that havent been editted further, can be turned off for clients with CRC bypass to save whatever processing power it uses)
UseVirtuProtect=true

[optional]
;物理攻击 面板上限
setDamageCap=199999
;魔攻/魔防 面板上限
setMAtkCap=1999
;命中上限
setAccCap=999
;回避上限
setAvdCap=999
;真实输出上限
setAtkOutCap=199999
;移速上限
speedMovementCap=140
;跳跃上限
jumpCap=123
;爬绳速度自适应：true=随移动速度变化；false=固定值
climbSpeedAuto=false
;爬绳基础速度系数
climbSpeed=1.0
;一种超级机制，不开启的话，升级属性点/技能点会停顿1秒，宠物捡取时攻击会停下来
useTubi=true
; 允许重复发言相同内容
talkRepeat=false
; 连续说话限制 (毫秒)
talkTime=2000

[debug]
debug=false
;免密模式，解除客户端密码限制（须先开启debug）
noPassword=false
